#!/usr/bin/env python3

"""
This module automates the build process for multiple Raspberry Pi 3 partitions 
using RODOS. It iterates through partition configurations that are specified 
in the module config_partition.py, swaps linker scripts such that each 
partition is loaded into the correct part of memory, compiles source files 
using the RODOS build-python scripts and generates binary images for booting.

!!! In order for this script to work, the correct linkerscripts are expected to
be located in the folder ./generated_scripts, generated by the script 
"generate_linkerscripts" !!!
"""


import os
import subprocess
import glob
import shutil
from config_partition import partition_configs
from generate_linkerscripts import generate_from_file
from pathlib import Path
import sys


def run_command(command):
    """
    Executes a shell command and terminates if the command fails.
    """
    print(f"Executing: {command}")
    result = subprocess.run(command, shell=True)
    if result.returncode != 0:
        print(f"Error executing: {command}")
        exit(1)


def build_image(base_name, source_file, elf_name, img_name):
    """
    Compiles a source file into an ELF executable using RODOS and
    converts the resulting ELF into a raw binary image (.img).
    """
    print(f"Building {base_name} with {source_file}...")
    run_command("mkdir -p build")
    run_command(f"cd build && rodos-executable.sh raspberrypi3 {source_file}")

    # 4. Binary Management
    if os.path.exists("build/tst"):
        if os.path.exists(Path("build") / elf_name):
            os.remove(Path("build") / elf_name)
        os.rename("build/tst", Path("build") / elf_name)

        run_command(f"arm-none-eabi-objcopy -O binary {Path("build")/elf_name} {img_name}")

    else:
        print(f"Error: 'tst' was not created for {base_name}")


def build_partitions(source_files, path_to_applications):
    """
    Orchestrates the build process for all partitions. It manages the RODOS
    linker script swapping, triggers the compilation for each partition,
    and also makes sure that the original system linker script is restored
    after each step.
    """
    print("source files built:")
    print(source_files)
    ld_folder = "./generated_scripts"

    print("\n--- Initializing RODOS Lib ---")
    run_command(f"rodos-lib.sh raspberrypi3")

    # Find all generated linker scripts
    ld_files = sorted(glob.glob(os.path.join(ld_folder, "*.ld")))

    if not ld_files:
        print(f"No linker scripts found in {ld_folder}!")
        return

    print(f"--- Found {len(ld_files)} linker scripts. Starting build ---\n")

    # Path to the system linker script to be overwritten
    script_dir = os.path.dirname(os.path.abspath(__file__))
    rodos_ld_path = os.path.abspath(
        os.path.join(
            script_dir,
            "../../../src/bare-metal/raspberrypi3/scripts/linkerscript.ld",
        )
    )
    rodos_ld_backup = rodos_ld_path + ".bak"

    for i, ld_path in enumerate(ld_files):
        print("-----------------------------")
        source_file = source_files[min(i, len(source_files) - 1)]

        # Names for output files
        base_name = f"partition_{i}"
        elf_name = f"tst_{base_name}"
        img_name = partition_configs[i]["partition_image_name"]
        abs_ld_path = os.path.abspath(ld_path)

        # Backup original template linker script
        if os.path.exists(rodos_ld_path):
            shutil.copy2(rodos_ld_path, rodos_ld_backup)

        # Overwrite linker script
        shutil.copy2(abs_ld_path, rodos_ld_path)

        # Build the image
        build_image(base_name, path_to_applications / source_file, elf_name, img_name)

        # Backup restoration
        if os.path.exists(rodos_ld_backup):
            shutil.move(rodos_ld_backup, rodos_ld_path)
            print(f"Restored {rodos_ld_path}")

        print("-----------------------------\n")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Error: Please provide a path to the folder containing "
            "the applications that should run as partitions!")
        sys.exit(1)

    path_to_applications = Path(sys.argv[1])



    # Generate the linker scripts necessary to load the partitions into RAM
    print("--- Generating Linker Scripts ---")
    generate_from_file(
        "../../../src/bare-metal/raspberrypi3/scripts/"
        "linkerscript_template_multiple_partitions.ld", 
        partition_configs
    )
    print("---------------------------------\n")



    # Read out the partition_sources (the .cpp files) from the config
    sources = []
    for partition in partition_configs:
        sources.append(partition["partition_source"])

    build_partitions(sources, path_to_applications)
